[build]
  publish = "."

[dev]
  framework = "#static"

[[edge_functions]]
  path = "/api/get-key"
  function = "get-key"

[[edge_functions]]
  path = "/api/gemini-image"
  function = "gemini-image"

[[edge_functions]]
  path = "/api/deepseek-chat"
  function = "deepseek-chat"

[[edge_functions]]
  path = "/api/gemini-chat"
  function = "gemini-chat"

[[edge_functions]]
  path = "/api/upload-media"
  function = "upload-media" 